
server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    data: classpath:data-h2.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: false